[package]
name = "lambda-webhook"
version = "0.1.0"
authors = ["Rim <rim.buei@gmail.com>"]
edition = "2018"

[dependencies]
http = "0.2.3"
lambda_runtime = "0.2.1"
log = "^0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple-error = "0.2.1"
simple_logger = "1.6.0"
