name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true
      - name: Run fmt check
        run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Run clippy check
        run: cargo clippy
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        rust:
          - stable
          - beta
          - nightly
        target:
          - ""
          - x86_64-unknown-linux-musl
        include:
          - rust: nightly
            allow_failure: true
        exclude:
          - os: macOS-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            rust: 1.40.0
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            rust: beta
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            rust: nightly
            target: x86_64-unknown-linux-musl
          - os: macOS-latest
            rust: 1.40.0
          - os: macOS-latest
            rust: beta
          - os: macOS-latest
            rust: nightly
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Build
        run: cargo build --all --verbose
        env:
          TARGET: ${{ matrix.target }}
        continue-on-error: ${{ matrix.allow_failure }}
      - name: Run tests
        run: cargo test --all --verbose
        env:
          TARGET: ${{ matrix.target }}
        continue-on-error: ${{ matrix.allow_failure }}
